# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agents_pb2 as agents__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agents_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RefinerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Process = channel.unary_unary(
                '/agents.RefinerService/Process',
                request_serializer=agents__pb2.RefineRequest.SerializeToString,
                response_deserializer=agents__pb2.FinalizeResponse.FromString,
                _registered_method=True)


class RefinerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Process(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RefinerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Process': grpc.unary_unary_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=agents__pb2.RefineRequest.FromString,
                    response_serializer=agents__pb2.FinalizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agents.RefinerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agents.RefinerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RefinerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agents.RefinerService/Process',
            agents__pb2.RefineRequest.SerializeToString,
            agents__pb2.FinalizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ResponderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Answer = channel.unary_unary(
                '/agents.ResponderService/Answer',
                request_serializer=agents__pb2.AnswerRequest.SerializeToString,
                response_deserializer=agents__pb2.AnswerResponse.FromString,
                _registered_method=True)
        self.Revise = channel.unary_unary(
                '/agents.ResponderService/Revise',
                request_serializer=agents__pb2.ReviseRequest.SerializeToString,
                response_deserializer=agents__pb2.AnswerResponse.FromString,
                _registered_method=True)


class ResponderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Answer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Revise(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResponderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Answer': grpc.unary_unary_rpc_method_handler(
                    servicer.Answer,
                    request_deserializer=agents__pb2.AnswerRequest.FromString,
                    response_serializer=agents__pb2.AnswerResponse.SerializeToString,
            ),
            'Revise': grpc.unary_unary_rpc_method_handler(
                    servicer.Revise,
                    request_deserializer=agents__pb2.ReviseRequest.FromString,
                    response_serializer=agents__pb2.AnswerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agents.ResponderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agents.ResponderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ResponderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Answer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agents.ResponderService/Answer',
            agents__pb2.AnswerRequest.SerializeToString,
            agents__pb2.AnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Revise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agents.ResponderService/Revise',
            agents__pb2.ReviseRequest.SerializeToString,
            agents__pb2.AnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FactCheckerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/agents.FactCheckerService/Check',
                request_serializer=agents__pb2.FactCheckRequest.SerializeToString,
                response_deserializer=agents__pb2.FactCheckResponse.FromString,
                _registered_method=True)


class FactCheckerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FactCheckerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=agents__pb2.FactCheckRequest.FromString,
                    response_serializer=agents__pb2.FactCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agents.FactCheckerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agents.FactCheckerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FactCheckerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agents.FactCheckerService/Check',
            agents__pb2.FactCheckRequest.SerializeToString,
            agents__pb2.FactCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HalluServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyze = channel.unary_unary(
                '/agents.HalluService/Analyze',
                request_serializer=agents__pb2.HalluRequest.SerializeToString,
                response_deserializer=agents__pb2.HalluResponse.FromString,
                _registered_method=True)
        self.AnalyzeAndFinalize = channel.unary_unary(
                '/agents.HalluService/AnalyzeAndFinalize',
                request_serializer=agents__pb2.HalluRequest.SerializeToString,
                response_deserializer=agents__pb2.FinalizeResponse.FromString,
                _registered_method=True)


class HalluServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Analyze(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeAndFinalize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HalluServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=agents__pb2.HalluRequest.FromString,
                    response_serializer=agents__pb2.HalluResponse.SerializeToString,
            ),
            'AnalyzeAndFinalize': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeAndFinalize,
                    request_deserializer=agents__pb2.HalluRequest.FromString,
                    response_serializer=agents__pb2.FinalizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agents.HalluService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agents.HalluService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HalluService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agents.HalluService/Analyze',
            agents__pb2.HalluRequest.SerializeToString,
            agents__pb2.HalluResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeAndFinalize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agents.HalluService/AnalyzeAndFinalize',
            agents__pb2.HalluRequest.SerializeToString,
            agents__pb2.FinalizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FinalizerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Finalize = channel.unary_unary(
                '/agents.FinalizerService/Finalize',
                request_serializer=agents__pb2.FinalizeRequest.SerializeToString,
                response_deserializer=agents__pb2.FinalizeResponse.FromString,
                _registered_method=True)


class FinalizerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Finalize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FinalizerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Finalize': grpc.unary_unary_rpc_method_handler(
                    servicer.Finalize,
                    request_deserializer=agents__pb2.FinalizeRequest.FromString,
                    response_serializer=agents__pb2.FinalizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agents.FinalizerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agents.FinalizerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FinalizerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Finalize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agents.FinalizerService/Finalize',
            agents__pb2.FinalizeRequest.SerializeToString,
            agents__pb2.FinalizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
